# Switches
set_property PACKAGE_PIN R2 [get_ports A]
   set_property IOSTANDARD LVCMOS33 [get_ports A]
set_property PACKAGE_PIN T1 [get_ports B]
   set_property IOSTANDARD LVCMOS33 [get_ports B]
set_property PACKAGE_PIN U1 [get_ports C]
   set_property IOSTANDARD LVCMOS33 [get_ports C] 
# LEDs
set_property PACKAGE_PIN V19 [get_ports W]   
    set_property IOSTANDARD LVCMOS33 [get_ports W]
set_property PACKAGE_PIN U19 [get_ports X]
    set_property IOSTANDARD LVCMOS33 [get_ports X]
set_property PACKAGE_PIN E19 [get_ports Y]
   set_property IOSTANDARD LVCMOS33 [get_ports Y]
set_property PACKAGE_PIN U16 [get_ports Z]
   set_property IOSTANDARD LVCMOS33 [get_ports Z]
   
#7 segment display
   set_property PACKAGE_PIN W7 [get_ports {segments[6]}]                    
       set_property IOSTANDARD LVCMOS33 [get_ports {segments[6]}]
   set_property PACKAGE_PIN W6 [get_ports {segments[5]}]                    
       set_property IOSTANDARD LVCMOS33 [get_ports {segments[5]}]
   set_property PACKAGE_PIN U8 [get_ports {segments[4]}]                    
       set_property IOSTANDARD LVCMOS33 [get_ports {segments[4]}]
   set_property PACKAGE_PIN V8 [get_ports {segments[3]}]                    
       set_property IOSTANDARD LVCMOS33 [get_ports {segments[3]}]
   set_property PACKAGE_PIN U5 [get_ports {segments[2]}]                    
       set_property IOSTANDARD LVCMOS33 [get_ports {segments[2]}]
   set_property PACKAGE_PIN V5 [get_ports {segments[1]}]                    
       set_property IOSTANDARD LVCMOS33 [get_ports {segments[1]}]
   set_property PACKAGE_PIN U7 [get_ports {segments[0]}]                    
       set_property IOSTANDARD LVCMOS33 [get_ports {segments[0]}]
   
   #set_property PACKAGE_PIN V7 [get_ports dp]                            
       #set_property IOSTANDARD LVCMOS33 [get_ports dp]
       
       set_property PACKAGE_PIN U2 [get_ports {an[0]}]					
           set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
       set_property PACKAGE_PIN U4 [get_ports {an[1]}]                    
           set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
       set_property PACKAGE_PIN V4 [get_ports {an[2]}]                    
           set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
       set_property PACKAGE_PIN W4 [get_ports {an[3]}]                    
           set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]
  
